version: "3"
services:
  mioty-bssci-adapter:
    build:
      context: .
      dockerfile: Dockerfile-devel
    ports:
      - "5005:5005/tcp"
    volumes:
      - ./:/mioty-bssci-adapter
    environment:
      - MQTT_SERVER=mosquitto:1883
      - TEST_MQTT_SERVER=mosquitto:1883
    networks:
      - test
    depends_on:
      - mosquitto

  mosquitto:
    container_name: mosquitto
    # 1.6 has allow_anonymous = true as default
    image: eclipse-mosquitto:1.6    
    networks:
      - test
    ports:
      - "1883:1883/tcp"
networks:
  test: