version: "3"
services:
  mioty-bssci-adapter:
    build:
      context: .
      dockerfile: Dockerfile-devel
    ports:
      - "5005:5005/tcp"
    volumes:
      - ./:/mioty-bssci-adapter
    links:
      - mosquitto
    environment:
      - MQTT_SERVER=tcp://mosquitto:1883
      - TEST_MQTT_SERVER=tcp://mosquitto:1883

  mosquitto:
    image: eclipse-mosquitto:latest
