// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: cmd/cmd.proto

package cmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation EUI, 8 bytes little endian
	BsEui uint64 `protobuf:"varint,1,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// Types that are valid to be assigned to V1:
	//
	//	*ProtoCommand_DlDataQue
	//	*ProtoCommand_DlDataRev
	//	*ProtoCommand_DlRxStatQry
	//	*ProtoCommand_AttPrp
	//	*ProtoCommand_DetPrp
	//	*ProtoCommand_ReqStatus
	//	*ProtoCommand_VmActivate
	//	*ProtoCommand_VmDeactivate
	//	*ProtoCommand_VmStatus
	V1            isProtoCommand_V1 `protobuf_oneof:"v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoCommand) Reset() {
	*x = ProtoCommand{}
	mi := &file_cmd_cmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoCommand) ProtoMessage() {}

func (x *ProtoCommand) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoCommand.ProtoReflect.Descriptor instead.
func (*ProtoCommand) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoCommand) GetBsEui() uint64 {
	if x != nil {
		return x.BsEui
	}
	return 0
}

func (x *ProtoCommand) GetV1() isProtoCommand_V1 {
	if x != nil {
		return x.V1
	}
	return nil
}

func (x *ProtoCommand) GetDlDataQue() *EnqueDownlink {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_DlDataQue); ok {
			return x.DlDataQue
		}
	}
	return nil
}

func (x *ProtoCommand) GetDlDataRev() *RevokeDownlink {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_DlDataRev); ok {
			return x.DlDataRev
		}
	}
	return nil
}

func (x *ProtoCommand) GetDlRxStatQry() *DownlinkRxStatusQuery {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_DlRxStatQry); ok {
			return x.DlRxStatQry
		}
	}
	return nil
}

func (x *ProtoCommand) GetAttPrp() *AttachPropagate {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_AttPrp); ok {
			return x.AttPrp
		}
	}
	return nil
}

func (x *ProtoCommand) GetDetPrp() *DetachPropagate {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_DetPrp); ok {
			return x.DetPrp
		}
	}
	return nil
}

func (x *ProtoCommand) GetReqStatus() *RequestStatus {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_ReqStatus); ok {
			return x.ReqStatus
		}
	}
	return nil
}

func (x *ProtoCommand) GetVmActivate() *EnableVariableMac {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_VmActivate); ok {
			return x.VmActivate
		}
	}
	return nil
}

func (x *ProtoCommand) GetVmDeactivate() *DisableVariableMac {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_VmDeactivate); ok {
			return x.VmDeactivate
		}
	}
	return nil
}

func (x *ProtoCommand) GetVmStatus() *RequestVariableMacStatus {
	if x != nil {
		if x, ok := x.V1.(*ProtoCommand_VmStatus); ok {
			return x.VmStatus
		}
	}
	return nil
}

type isProtoCommand_V1 interface {
	isProtoCommand_V1()
}

type ProtoCommand_DlDataQue struct {
	// Enque downlink
	DlDataQue *EnqueDownlink `protobuf:"bytes,3,opt,name=dl_data_que,json=dlDataQue,proto3,oneof"`
}

type ProtoCommand_DlDataRev struct {
	// Revoke downlink
	DlDataRev *RevokeDownlink `protobuf:"bytes,4,opt,name=dl_data_rev,json=dlDataRev,proto3,oneof"`
}

type ProtoCommand_DlRxStatQry struct {
	// Downlink RX status query
	DlRxStatQry *DownlinkRxStatusQuery `protobuf:"bytes,5,opt,name=dl_rx_stat_qry,json=dlRxStatQry,proto3,oneof"`
}

type ProtoCommand_AttPrp struct {
	// Propagate attach
	AttPrp *AttachPropagate `protobuf:"bytes,6,opt,name=att_prp,json=attPrp,proto3,oneof"`
}

type ProtoCommand_DetPrp struct {
	// Propagate detach
	DetPrp *DetachPropagate `protobuf:"bytes,7,opt,name=det_prp,json=detPrp,proto3,oneof"`
}

type ProtoCommand_ReqStatus struct {
	// Status
	ReqStatus *RequestStatus `protobuf:"bytes,8,opt,name=req_status,json=reqStatus,proto3,oneof"`
}

type ProtoCommand_VmActivate struct {
	// VM Activate
	VmActivate *EnableVariableMac `protobuf:"bytes,9,opt,name=vm_activate,json=vmActivate,proto3,oneof"`
}

type ProtoCommand_VmDeactivate struct {
	// VM Deactivate
	VmDeactivate *DisableVariableMac `protobuf:"bytes,10,opt,name=vm_deactivate,json=vmDeactivate,proto3,oneof"`
}

type ProtoCommand_VmStatus struct {
	// VM Status
	VmStatus *RequestVariableMacStatus `protobuf:"bytes,11,opt,name=vm_status,json=vmStatus,proto3,oneof"`
}

func (*ProtoCommand_DlDataQue) isProtoCommand_V1() {}

func (*ProtoCommand_DlDataRev) isProtoCommand_V1() {}

func (*ProtoCommand_DlRxStatQry) isProtoCommand_V1() {}

func (*ProtoCommand_AttPrp) isProtoCommand_V1() {}

func (*ProtoCommand_DetPrp) isProtoCommand_V1() {}

func (*ProtoCommand_ReqStatus) isProtoCommand_V1() {}

func (*ProtoCommand_VmActivate) isProtoCommand_V1() {}

func (*ProtoCommand_VmDeactivate) isProtoCommand_V1() {}

func (*ProtoCommand_VmStatus) isProtoCommand_V1() {}

// Downlink data queue
type EnqueDownlink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui uint64 `protobuf:"varint,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// Assigned queue ID for reference
	DlQueId uint64 `protobuf:"varint,3,opt,name=dl_que_id,json=dlQueId,proto3" json:"dl_que_id,omitempty"`
	// Priority, higher values are prioritized, optional, default 0
	Priority *float32 `protobuf:"fixed32,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	// MPF header byte, 1 byte
	Format *uint32 `protobuf:"varint,5,opt,name=format,proto3,oneof" json:"format,omitempty"`
	// Downlink payload.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*EnqueDownlink_Ack
	//	*EnqueDownlink_Data
	//	*EnqueDownlink_DataEnc
	Payload isEnqueDownlink_Payload `protobuf_oneof:"payload"`
	// True to request End Point response, optional
	ResponseExp *bool `protobuf:"varint,9,opt,name=response_exp,json=responseExp,proto3,oneof" json:"response_exp,omitempty"`
	// True to request priority End Point response, optional
	ResponsePrio *bool `protobuf:"varint,10,opt,name=response_prio,json=responsePrio,proto3,oneof" json:"response_prio,omitempty"`
	// True to request further End Point DL window, optional
	ReqDlWindow *bool `protobuf:"varint,11,opt,name=req_dl_window,json=reqDlWindow,proto3,oneof" json:"req_dl_window,omitempty"`
	// True to send downlink only if End Point expects a response, optional
	OnlyIfExpected *bool `protobuf:"varint,12,opt,name=only_if_expected,json=onlyIfExpected,proto3,oneof" json:"only_if_expected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueDownlink) Reset() {
	*x = EnqueDownlink{}
	mi := &file_cmd_cmd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueDownlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueDownlink) ProtoMessage() {}

func (x *EnqueDownlink) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueDownlink.ProtoReflect.Descriptor instead.
func (*EnqueDownlink) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueDownlink) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

func (x *EnqueDownlink) GetDlQueId() uint64 {
	if x != nil {
		return x.DlQueId
	}
	return 0
}

func (x *EnqueDownlink) GetPriority() float32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *EnqueDownlink) GetFormat() uint32 {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return 0
}

func (x *EnqueDownlink) GetPayload() isEnqueDownlink_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueDownlink) GetAck() *Acknowledgement {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *EnqueDownlink) GetData() *DownlinkData {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *EnqueDownlink) GetDataEnc() *DownlinkDataEncrypted {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_DataEnc); ok {
			return x.DataEnc
		}
	}
	return nil
}

func (x *EnqueDownlink) GetResponseExp() bool {
	if x != nil && x.ResponseExp != nil {
		return *x.ResponseExp
	}
	return false
}

func (x *EnqueDownlink) GetResponsePrio() bool {
	if x != nil && x.ResponsePrio != nil {
		return *x.ResponsePrio
	}
	return false
}

func (x *EnqueDownlink) GetReqDlWindow() bool {
	if x != nil && x.ReqDlWindow != nil {
		return *x.ReqDlWindow
	}
	return false
}

func (x *EnqueDownlink) GetOnlyIfExpected() bool {
	if x != nil && x.OnlyIfExpected != nil {
		return *x.OnlyIfExpected
	}
	return false
}

type isEnqueDownlink_Payload interface {
	isEnqueDownlink_Payload()
}

type EnqueDownlink_Ack struct {
	// Uplink acknowledgement
	Ack *Acknowledgement `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

type EnqueDownlink_Data struct {
	// Unencrypted payload
	Data *DownlinkData `protobuf:"bytes,7,opt,name=data,proto3,oneof"`
}

type EnqueDownlink_DataEnc struct {
	// Encrypted payload
	DataEnc *DownlinkDataEncrypted `protobuf:"bytes,8,opt,name=data_enc,json=dataEnc,proto3,oneof"`
}

func (*EnqueDownlink_Ack) isEnqueDownlink_Payload() {}

func (*EnqueDownlink_Data) isEnqueDownlink_Payload() {}

func (*EnqueDownlink_DataEnc) isEnqueDownlink_Payload() {}

// Uplink acknowledgement
type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_cmd_cmd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{2}
}

// Unencrypted payload
type DownlinkData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User data
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkData) Reset() {
	*x = DownlinkData{}
	mi := &file_cmd_cmd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkData) ProtoMessage() {}

func (x *DownlinkData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkData.ProtoReflect.Descriptor instead.
func (*DownlinkData) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{3}
}

func (x *DownlinkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Encrypted payload
type DownlinkDataEncrypted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data for each of the m packet counters
	Data [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Endnode packet counter for which the respective data entry is valid
	PacketCnt     []uint32 `protobuf:"varint,2,rep,packed,name=packet_cnt,json=packetCnt,proto3" json:"packet_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkDataEncrypted) Reset() {
	*x = DownlinkDataEncrypted{}
	mi := &file_cmd_cmd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkDataEncrypted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkDataEncrypted) ProtoMessage() {}

func (x *DownlinkDataEncrypted) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkDataEncrypted.ProtoReflect.Descriptor instead.
func (*DownlinkDataEncrypted) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{4}
}

func (x *DownlinkDataEncrypted) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownlinkDataEncrypted) GetPacketCnt() []uint32 {
	if x != nil {
		return x.PacketCnt
	}
	return nil
}

// Downlink data revoke
type RevokeDownlink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui uint64 `protobuf:"varint,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// Assigned queue ID for reference
	DlQueId       uint64 `protobuf:"varint,3,opt,name=dl_que_id,json=dlQueId,proto3" json:"dl_que_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDownlink) Reset() {
	*x = RevokeDownlink{}
	mi := &file_cmd_cmd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDownlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDownlink) ProtoMessage() {}

func (x *RevokeDownlink) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDownlink.ProtoReflect.Descriptor instead.
func (*RevokeDownlink) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeDownlink) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

func (x *RevokeDownlink) GetDlQueId() uint64 {
	if x != nil {
		return x.DlQueId
	}
	return 0
}

// Downlink rx status query
type DownlinkRxStatusQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui    uint64 `protobuf:"varint,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkRxStatusQuery) Reset() {
	*x = DownlinkRxStatusQuery{}
	mi := &file_cmd_cmd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkRxStatusQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkRxStatusQuery) ProtoMessage() {}

func (x *DownlinkRxStatusQuery) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkRxStatusQuery.ProtoReflect.Descriptor instead.
func (*DownlinkRxStatusQuery) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{6}
}

func (x *DownlinkRxStatusQuery) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

type AttachPropagate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui uint64 `protobuf:"varint,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// End Point short address
	ShAddr uint32 `protobuf:"varint,3,opt,name=sh_addr,json=shAddr,proto3" json:"sh_addr,omitempty"`
	// 16 Byte End Point network session key
	NwkSessionKey []byte `protobuf:"bytes,4,opt,name=nwk_session_key,json=nwkSessionKey,proto3" json:"nwk_session_key,omitempty"`
	// Packet counter.
	LastPacketCnt int32 `protobuf:"varint,5,opt,name=last_packet_cnt,json=lastPacketCnt,proto3" json:"last_packet_cnt,omitempty"`
	// True if End Point is bidirectional
	Bidi bool `protobuf:"varint,6,opt,name=bidi,proto3" json:"bidi,omitempty"`
	// True if End Point uses dual channel mode
	DualChannel bool `protobuf:"varint,7,opt,name=dual_channel,json=dualChannel,proto3" json:"dual_channel,omitempty"`
	// True if End Point uses DL repetition
	Repetition bool `protobuf:"varint,8,opt,name=repetition,proto3" json:"repetition,omitempty"`
	// True if End Point uses wide carrier offset
	WideCarrOff bool `protobuf:"varint,9,opt,name=wide_carr_off,json=wideCarrOff,proto3" json:"wide_carr_off,omitempty"`
	// True if End Point uses long DL interblock distance
	LongBlkDist   bool `protobuf:"varint,10,opt,name=long_blk_dist,json=longBlkDist,proto3" json:"long_blk_dist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPropagate) Reset() {
	*x = AttachPropagate{}
	mi := &file_cmd_cmd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPropagate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPropagate) ProtoMessage() {}

func (x *AttachPropagate) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPropagate.ProtoReflect.Descriptor instead.
func (*AttachPropagate) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{7}
}

func (x *AttachPropagate) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

func (x *AttachPropagate) GetShAddr() uint32 {
	if x != nil {
		return x.ShAddr
	}
	return 0
}

func (x *AttachPropagate) GetNwkSessionKey() []byte {
	if x != nil {
		return x.NwkSessionKey
	}
	return nil
}

func (x *AttachPropagate) GetLastPacketCnt() int32 {
	if x != nil {
		return x.LastPacketCnt
	}
	return 0
}

func (x *AttachPropagate) GetBidi() bool {
	if x != nil {
		return x.Bidi
	}
	return false
}

func (x *AttachPropagate) GetDualChannel() bool {
	if x != nil {
		return x.DualChannel
	}
	return false
}

func (x *AttachPropagate) GetRepetition() bool {
	if x != nil {
		return x.Repetition
	}
	return false
}

func (x *AttachPropagate) GetWideCarrOff() bool {
	if x != nil {
		return x.WideCarrOff
	}
	return false
}

func (x *AttachPropagate) GetLongBlkDist() bool {
	if x != nil {
		return x.LongBlkDist
	}
	return false
}

type DetachPropagate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui    uint64 `protobuf:"varint,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachPropagate) Reset() {
	*x = DetachPropagate{}
	mi := &file_cmd_cmd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachPropagate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachPropagate) ProtoMessage() {}

func (x *DetachPropagate) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachPropagate.ProtoReflect.Descriptor instead.
func (*DetachPropagate) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{8}
}

func (x *DetachPropagate) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

type RequestStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStatus) Reset() {
	*x = RequestStatus{}
	mi := &file_cmd_cmd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStatus) ProtoMessage() {}

func (x *RequestStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStatus.ProtoReflect.Descriptor instead.
func (*RequestStatus) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{9}
}

type EnableVariableMac struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MAC-Type of the intended Variable MAC
	MacType       int64 `protobuf:"varint,2,opt,name=mac_type,json=macType,proto3" json:"mac_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableVariableMac) Reset() {
	*x = EnableVariableMac{}
	mi := &file_cmd_cmd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableVariableMac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableVariableMac) ProtoMessage() {}

func (x *EnableVariableMac) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableVariableMac.ProtoReflect.Descriptor instead.
func (*EnableVariableMac) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{10}
}

func (x *EnableVariableMac) GetMacType() int64 {
	if x != nil {
		return x.MacType
	}
	return 0
}

type DisableVariableMac struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MAC-Type of the intended Variable MAC
	MacType       int64 `protobuf:"varint,2,opt,name=mac_type,json=macType,proto3" json:"mac_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableVariableMac) Reset() {
	*x = DisableVariableMac{}
	mi := &file_cmd_cmd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableVariableMac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableVariableMac) ProtoMessage() {}

func (x *DisableVariableMac) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableVariableMac.ProtoReflect.Descriptor instead.
func (*DisableVariableMac) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{11}
}

func (x *DisableVariableMac) GetMacType() int64 {
	if x != nil {
		return x.MacType
	}
	return 0
}

type RequestVariableMacStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVariableMacStatus) Reset() {
	*x = RequestVariableMacStatus{}
	mi := &file_cmd_cmd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVariableMacStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVariableMacStatus) ProtoMessage() {}

func (x *RequestVariableMacStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_cmd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVariableMacStatus.ProtoReflect.Descriptor instead.
func (*RequestVariableMacStatus) Descriptor() ([]byte, []int) {
	return file_cmd_cmd_proto_rawDescGZIP(), []int{12}
}

var File_cmd_cmd_proto protoreflect.FileDescriptor

var file_cmd_cmd_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x63, 0x6d, 0x64, 0x22, 0xab, 0x04, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x73, 0x5f, 0x65, 0x75, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x73, 0x45, 0x75, 0x69, 0x12, 0x34, 0x0a, 0x0b,
	0x64, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x71, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x09, 0x64, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x51,
	0x75, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x64, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x65,
	0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x52, 0x65,
	0x76, 0x6f, 0x6b, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x09,
	0x64, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x76, 0x12, 0x41, 0x0a, 0x0e, 0x64, 0x6c, 0x5f,
	0x72, 0x78, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x5f, 0x71, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b,
	0x52, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52,
	0x0b, 0x64, 0x6c, 0x52, 0x78, 0x53, 0x74, 0x61, 0x74, 0x51, 0x72, 0x79, 0x12, 0x2f, 0x0a, 0x07,
	0x61, 0x74, 0x74, 0x5f, 0x70, 0x72, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x63, 0x6d, 0x64, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x61, 0x74, 0x74, 0x50, 0x72, 0x70, 0x12, 0x2f, 0x0a,
	0x07, 0x64, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x70, 0x61,
	0x67, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x74, 0x50, 0x72, 0x70, 0x12, 0x33,
	0x0a, 0x0a, 0x72, 0x65, 0x71, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x71, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0b, 0x76, 0x6d, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x63,
	0x48, 0x00, 0x52, 0x0a, 0x76, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x3e,
	0x0a, 0x0d, 0x76, 0x6d, 0x5f, 0x64, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x63, 0x48, 0x00,
	0x52, 0x0c, 0x76, 0x6d, 0x44, 0x65, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x3c,
	0x0a, 0x09, 0x76, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x48, 0x00, 0x52, 0x08, 0x76, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x04, 0x0a, 0x02,
	0x76, 0x31, 0x22, 0xad, 0x04, 0x0a, 0x0d, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x65, 0x75, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x6e, 0x6f,
	0x64, 0x65, 0x45, 0x75, 0x69, 0x12, 0x1a, 0x0a, 0x09, 0x64, 0x6c, 0x5f, 0x71, 0x75, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x64, 0x6c, 0x51, 0x75, 0x65, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x02, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x88, 0x01, 0x01, 0x12,
	0x28, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63,
	0x6d, 0x64, 0x2e, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x37, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x69, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x12, 0x26, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x78, 0x70,
	0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x70, 0x72, 0x69, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x48, 0x04, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x69, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a,
	0x0d, 0x72, 0x65, 0x71, 0x5f, 0x64, 0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x44, 0x6c, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x10, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x69,
	0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x06, 0x52, 0x0e, 0x6f, 0x6e, 0x6c, 0x79, 0x49, 0x66, 0x45, 0x78, 0x70, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x42, 0x10, 0x0a, 0x0e, 0x5f,
	0x72, 0x65, 0x71, 0x5f, 0x64, 0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x42, 0x13, 0x0a,
	0x11, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x69, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x15, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x5f, 0x63, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x43, 0x6e, 0x74, 0x22, 0x4d, 0x0a, 0x0e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x65, 0x75, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x6e,
	0x64, 0x6e, 0x6f, 0x64, 0x65, 0x45, 0x75, 0x69, 0x12, 0x1a, 0x0a, 0x09, 0x64, 0x6c, 0x5f, 0x71,
	0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x64, 0x6c, 0x51,
	0x75, 0x65, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b,
	0x52, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1f, 0x0a,
	0x0b, 0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x75, 0x69, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x45, 0x75, 0x69, 0x22, 0xba,
	0x02, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x75,
	0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65,
	0x45, 0x75, 0x69, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x68, 0x41, 0x64, 0x64, 0x72, 0x12, 0x26, 0x0a, 0x0f,
	0x6e, 0x77, 0x6b, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x6e, 0x77, 0x6b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x5f, 0x63, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6c,
	0x61, 0x73, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x69, 0x64, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x69, 0x64, 0x69,
	0x12, 0x21, 0x0a, 0x0c, 0x64, 0x75, 0x61, 0x6c, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x64, 0x75, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x77, 0x69, 0x64, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x72,
	0x5f, 0x6f, 0x66, 0x66, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69, 0x64, 0x65,
	0x43, 0x61, 0x72, 0x72, 0x4f, 0x66, 0x66, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x6f, 0x6e, 0x67, 0x5f,
	0x62, 0x6c, 0x6b, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x6c, 0x6f, 0x6e, 0x67, 0x42, 0x6c, 0x6b, 0x44, 0x69, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x0f, 0x44,
	0x65, 0x74, 0x61, 0x63, 0x68, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x75, 0x69, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x45, 0x75, 0x69, 0x22,
	0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x2e, 0x0a, 0x11, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x4d, 0x61, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x63, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x2f, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x4d, 0x61, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x63, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x26, 0x5a,
	0x24, 0x6d, 0x69, 0x6f, 0x74, 0x79, 0x2d, 0x62, 0x73, 0x73, 0x63, 0x69, 0x2d, 0x61, 0x64, 0x61,
	0x70, 0x74, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x63, 0x6d, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cmd_cmd_proto_rawDescOnce sync.Once
	file_cmd_cmd_proto_rawDescData []byte
)

func file_cmd_cmd_proto_rawDescGZIP() []byte {
	file_cmd_cmd_proto_rawDescOnce.Do(func() {
		file_cmd_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_cmd_proto_rawDesc), len(file_cmd_cmd_proto_rawDesc)))
	})
	return file_cmd_cmd_proto_rawDescData
}

var file_cmd_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cmd_cmd_proto_goTypes = []any{
	(*ProtoCommand)(nil),             // 0: cmd.ProtoCommand
	(*EnqueDownlink)(nil),            // 1: cmd.EnqueDownlink
	(*Acknowledgement)(nil),          // 2: cmd.Acknowledgement
	(*DownlinkData)(nil),             // 3: cmd.DownlinkData
	(*DownlinkDataEncrypted)(nil),    // 4: cmd.DownlinkDataEncrypted
	(*RevokeDownlink)(nil),           // 5: cmd.RevokeDownlink
	(*DownlinkRxStatusQuery)(nil),    // 6: cmd.DownlinkRxStatusQuery
	(*AttachPropagate)(nil),          // 7: cmd.AttachPropagate
	(*DetachPropagate)(nil),          // 8: cmd.DetachPropagate
	(*RequestStatus)(nil),            // 9: cmd.RequestStatus
	(*EnableVariableMac)(nil),        // 10: cmd.EnableVariableMac
	(*DisableVariableMac)(nil),       // 11: cmd.DisableVariableMac
	(*RequestVariableMacStatus)(nil), // 12: cmd.RequestVariableMacStatus
}
var file_cmd_cmd_proto_depIdxs = []int32{
	1,  // 0: cmd.ProtoCommand.dl_data_que:type_name -> cmd.EnqueDownlink
	5,  // 1: cmd.ProtoCommand.dl_data_rev:type_name -> cmd.RevokeDownlink
	6,  // 2: cmd.ProtoCommand.dl_rx_stat_qry:type_name -> cmd.DownlinkRxStatusQuery
	7,  // 3: cmd.ProtoCommand.att_prp:type_name -> cmd.AttachPropagate
	8,  // 4: cmd.ProtoCommand.det_prp:type_name -> cmd.DetachPropagate
	9,  // 5: cmd.ProtoCommand.req_status:type_name -> cmd.RequestStatus
	10, // 6: cmd.ProtoCommand.vm_activate:type_name -> cmd.EnableVariableMac
	11, // 7: cmd.ProtoCommand.vm_deactivate:type_name -> cmd.DisableVariableMac
	12, // 8: cmd.ProtoCommand.vm_status:type_name -> cmd.RequestVariableMacStatus
	2,  // 9: cmd.EnqueDownlink.ack:type_name -> cmd.Acknowledgement
	3,  // 10: cmd.EnqueDownlink.data:type_name -> cmd.DownlinkData
	4,  // 11: cmd.EnqueDownlink.data_enc:type_name -> cmd.DownlinkDataEncrypted
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cmd_cmd_proto_init() }
func file_cmd_cmd_proto_init() {
	if File_cmd_cmd_proto != nil {
		return
	}
	file_cmd_cmd_proto_msgTypes[0].OneofWrappers = []any{
		(*ProtoCommand_DlDataQue)(nil),
		(*ProtoCommand_DlDataRev)(nil),
		(*ProtoCommand_DlRxStatQry)(nil),
		(*ProtoCommand_AttPrp)(nil),
		(*ProtoCommand_DetPrp)(nil),
		(*ProtoCommand_ReqStatus)(nil),
		(*ProtoCommand_VmActivate)(nil),
		(*ProtoCommand_VmDeactivate)(nil),
		(*ProtoCommand_VmStatus)(nil),
	}
	file_cmd_cmd_proto_msgTypes[1].OneofWrappers = []any{
		(*EnqueDownlink_Ack)(nil),
		(*EnqueDownlink_Data)(nil),
		(*EnqueDownlink_DataEnc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_cmd_proto_rawDesc), len(file_cmd_cmd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_cmd_proto_goTypes,
		DependencyIndexes: file_cmd_cmd_proto_depIdxs,
		MessageInfos:      file_cmd_cmd_proto_msgTypes,
	}.Build()
	File_cmd_cmd_proto = out.File
	file_cmd_cmd_proto_goTypes = nil
	file_cmd_cmd_proto_depIdxs = nil
}
