// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: msg/basestation.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionState int32

const (
	ConnectionState_OFFLINE ConnectionState = 0
	ConnectionState_ONLINE  ConnectionState = 1
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
	}
	ConnectionState_value = map[string]int32{
		"OFFLINE": 0,
		"ONLINE":  1,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_basestation_proto_enumTypes[0].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_msg_basestation_proto_enumTypes[0]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_msg_basestation_proto_rawDescGZIP(), []int{0}
}

type ProtoBasestationState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation EUI, 8 bytes little endian
	BsEui uint64 `protobuf:"varint,1,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// ConnectionState
	State         ConnectionState `protobuf:"varint,2,opt,name=state,proto3,enum=msg.ConnectionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoBasestationState) Reset() {
	*x = ProtoBasestationState{}
	mi := &file_msg_basestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBasestationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBasestationState) ProtoMessage() {}

func (x *ProtoBasestationState) ProtoReflect() protoreflect.Message {
	mi := &file_msg_basestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBasestationState.ProtoReflect.Descriptor instead.
func (*ProtoBasestationState) Descriptor() ([]byte, []int) {
	return file_msg_basestation_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoBasestationState) GetBsEui() uint64 {
	if x != nil {
		return x.BsEui
	}
	return 0
}

func (x *ProtoBasestationState) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_OFFLINE
}

type ProtoBasestationMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation EUI, 8 bytes little endian
	BsEui uint64 `protobuf:"varint,1,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// Message.
	//
	// Types that are valid to be assigned to V1:
	//
	//	*ProtoBasestationMessage_Con
	//	*ProtoBasestationMessage_Status
	//	*ProtoBasestationMessage_VmStatus
	V1            isProtoBasestationMessage_V1 `protobuf_oneof:"v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoBasestationMessage) Reset() {
	*x = ProtoBasestationMessage{}
	mi := &file_msg_basestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoBasestationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBasestationMessage) ProtoMessage() {}

func (x *ProtoBasestationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_basestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBasestationMessage.ProtoReflect.Descriptor instead.
func (*ProtoBasestationMessage) Descriptor() ([]byte, []int) {
	return file_msg_basestation_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoBasestationMessage) GetBsEui() uint64 {
	if x != nil {
		return x.BsEui
	}
	return 0
}

func (x *ProtoBasestationMessage) GetV1() isProtoBasestationMessage_V1 {
	if x != nil {
		return x.V1
	}
	return nil
}

func (x *ProtoBasestationMessage) GetCon() *BasestationConnection {
	if x != nil {
		if x, ok := x.V1.(*ProtoBasestationMessage_Con); ok {
			return x.Con
		}
	}
	return nil
}

func (x *ProtoBasestationMessage) GetStatus() *BasestationStatus {
	if x != nil {
		if x, ok := x.V1.(*ProtoBasestationMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ProtoBasestationMessage) GetVmStatus() *BasestationVariableMacStatus {
	if x != nil {
		if x, ok := x.V1.(*ProtoBasestationMessage_VmStatus); ok {
			return x.VmStatus
		}
	}
	return nil
}

type isProtoBasestationMessage_V1 interface {
	isProtoBasestationMessage_V1()
}

type ProtoBasestationMessage_Con struct {
	// Connect
	Con *BasestationConnection `protobuf:"bytes,3,opt,name=con,proto3,oneof"`
}

type ProtoBasestationMessage_Status struct {
	// Status
	Status *BasestationStatus `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type ProtoBasestationMessage_VmStatus struct {
	// VM Status
	VmStatus *BasestationVariableMacStatus `protobuf:"bytes,5,opt,name=vm_status,json=vmStatus,proto3,oneof"`
}

func (*ProtoBasestationMessage_Con) isProtoBasestationMessage_V1() {}

func (*ProtoBasestationMessage_Status) isProtoBasestationMessage_V1() {}

func (*ProtoBasestationMessage_VmStatus) isProtoBasestationMessage_V1() {}

// Connect
type BasestationConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix UTC system time
	Ts *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	// Requested protocol version, major.minor.patch
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// True if Base Station is bidirectional
	Bidi bool `protobuf:"varint,4,opt,name=bidi,proto3" json:"bidi,omitempty"`
	// Vendor of the Base Station, optional
	Vendor *string `protobuf:"bytes,5,opt,name=vendor,proto3,oneof" json:"vendor,omitempty"`
	// Model of the Base Station, optional
	Model *string `protobuf:"bytes,6,opt,name=model,proto3,oneof" json:"model,omitempty"`
	// Name of the Base Station, optional
	Name *string `protobuf:"bytes,7,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Software version, optional
	SwVersion     *string `protobuf:"bytes,8,opt,name=sw_version,json=swVersion,proto3,oneof" json:"sw_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasestationConnection) Reset() {
	*x = BasestationConnection{}
	mi := &file_msg_basestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasestationConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasestationConnection) ProtoMessage() {}

func (x *BasestationConnection) ProtoReflect() protoreflect.Message {
	mi := &file_msg_basestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasestationConnection.ProtoReflect.Descriptor instead.
func (*BasestationConnection) Descriptor() ([]byte, []int) {
	return file_msg_basestation_proto_rawDescGZIP(), []int{2}
}

func (x *BasestationConnection) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *BasestationConnection) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BasestationConnection) GetBidi() bool {
	if x != nil {
		return x.Bidi
	}
	return false
}

func (x *BasestationConnection) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *BasestationConnection) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *BasestationConnection) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BasestationConnection) GetSwVersion() string {
	if x != nil && x.SwVersion != nil {
		return *x.SwVersion
	}
	return ""
}

// Status
type BasestationStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status code, using POSIX error numbers, 0 for ok
	StatusCode uint32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// Status message
	StatusMsg string `protobuf:"bytes,3,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
	// Unix UTC system time
	Ts *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	// Fraction of TX time, sliding window over one hour
	DutyCycle float32 `protobuf:"fixed32,5,opt,name=duty_cycle,json=dutyCycle,proto3" json:"duty_cycle,omitempty"`
	// Geographic location [Latitude, Longitude, Altitude], optional
	GeoLocation *GeoLocation `protobuf:"bytes,6,opt,name=geo_location,json=geoLocation,proto3,oneof" json:"geo_location,omitempty"`
	// System uptime in seconds, optional
	Uptime *uint64 `protobuf:"varint,7,opt,name=uptime,proto3,oneof" json:"uptime,omitempty"`
	// System temperature in degree Celsius, optional
	Temp *float64 `protobuf:"fixed64,8,opt,name=temp,proto3,oneof" json:"temp,omitempty"`
	// CPU utilization, normalized to 1.0 for all cores, optional
	Cpu *float64 `protobuf:"fixed64,9,opt,name=cpu,proto3,oneof" json:"cpu,omitempty"`
	// Memory utilization, normalized to 1.0, optional
	Memory        *float64 `protobuf:"fixed64,10,opt,name=memory,proto3,oneof" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasestationStatus) Reset() {
	*x = BasestationStatus{}
	mi := &file_msg_basestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasestationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasestationStatus) ProtoMessage() {}

func (x *BasestationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_msg_basestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasestationStatus.ProtoReflect.Descriptor instead.
func (*BasestationStatus) Descriptor() ([]byte, []int) {
	return file_msg_basestation_proto_rawDescGZIP(), []int{3}
}

func (x *BasestationStatus) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BasestationStatus) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

func (x *BasestationStatus) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *BasestationStatus) GetDutyCycle() float32 {
	if x != nil {
		return x.DutyCycle
	}
	return 0
}

func (x *BasestationStatus) GetGeoLocation() *GeoLocation {
	if x != nil {
		return x.GeoLocation
	}
	return nil
}

func (x *BasestationStatus) GetUptime() uint64 {
	if x != nil && x.Uptime != nil {
		return *x.Uptime
	}
	return 0
}

func (x *BasestationStatus) GetTemp() float64 {
	if x != nil && x.Temp != nil {
		return *x.Temp
	}
	return 0
}

func (x *BasestationStatus) GetCpu() float64 {
	if x != nil && x.Cpu != nil {
		return *x.Cpu
	}
	return 0
}

func (x *BasestationStatus) GetMemory() float64 {
	if x != nil && x.Memory != nil {
		return *x.Memory
	}
	return 0
}

type GeoLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float32                `protobuf:"fixed32,3,opt,name=alt,proto3" json:"alt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_msg_basestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_msg_basestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_msg_basestation_proto_rawDescGZIP(), []int{4}
}

func (x *GeoLocation) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GeoLocation) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *GeoLocation) GetAlt() float32 {
	if x != nil {
		return x.Alt
	}
	return 0
}

// The VM Status represents a list of the activated MAC-Types.
type BasestationVariableMacStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of activated macTypes
	MacTypes      []int64 `protobuf:"varint,2,rep,packed,name=mac_types,json=macTypes,proto3" json:"mac_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasestationVariableMacStatus) Reset() {
	*x = BasestationVariableMacStatus{}
	mi := &file_msg_basestation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasestationVariableMacStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasestationVariableMacStatus) ProtoMessage() {}

func (x *BasestationVariableMacStatus) ProtoReflect() protoreflect.Message {
	mi := &file_msg_basestation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasestationVariableMacStatus.ProtoReflect.Descriptor instead.
func (*BasestationVariableMacStatus) Descriptor() ([]byte, []int) {
	return file_msg_basestation_proto_rawDescGZIP(), []int{5}
}

func (x *BasestationVariableMacStatus) GetMacTypes() []int64 {
	if x != nil {
		return x.MacTypes
	}
	return nil
}

var File_msg_basestation_proto protoreflect.FileDescriptor

var file_msg_basestation_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a,
	0x15, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x73, 0x5f, 0x65, 0x75, 0x69,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x73, 0x45, 0x75, 0x69, 0x12, 0x2a, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0xda, 0x01, 0x0a, 0x17, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x73, 0x5f, 0x65, 0x75, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x73, 0x45, 0x75, 0x69, 0x12, 0x2e, 0x0a, 0x03,
	0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x03, 0x63, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x40,
	0x0a, 0x09, 0x76, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x63, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x08, 0x76, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x42, 0x04, 0x0a, 0x02, 0x76, 0x31, 0x22, 0x93, 0x02, 0x0a, 0x15, 0x42, 0x61, 0x73, 0x65, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x69, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x69, 0x64, 0x69, 0x12, 0x1b, 0x0a, 0x06, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x88,
	0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x73,
	0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x03, 0x52, 0x09, 0x73, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x73, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xfa, 0x02, 0x0a,
	0x11, 0x42, 0x61, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d,
	0x73, 0x67, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x64, 0x75, 0x74, 0x79, 0x5f, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x64, 0x75, 0x74, 0x79, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x38, 0x0a,
	0x0c, 0x67, 0x65, 0x6f, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x47, 0x65, 0x6f, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x65, 0x6f, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x02, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a,
	0x03, 0x63, 0x70, 0x75, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x48, 0x03, 0x52, 0x03, 0x63, 0x70,
	0x75, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x88, 0x01,
	0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x67, 0x65, 0x6f, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x63, 0x70, 0x75, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x22, 0x43, 0x0a, 0x0b, 0x47, 0x65, 0x6f,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x61, 0x6c, 0x74, 0x22, 0x3b,
	0x0a, 0x1c, 0x42, 0x61, 0x73, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x61, 0x63, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x61, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x08, 0x6d, 0x61, 0x63, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x2a, 0x0a, 0x0f, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f,
	0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x42, 0x26, 0x5a, 0x24, 0x6d, 0x69, 0x6f, 0x74, 0x79,
	0x2d, 0x62, 0x73, 0x73, 0x63, 0x69, 0x2d, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x73, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_msg_basestation_proto_rawDescOnce sync.Once
	file_msg_basestation_proto_rawDescData []byte
)

func file_msg_basestation_proto_rawDescGZIP() []byte {
	file_msg_basestation_proto_rawDescOnce.Do(func() {
		file_msg_basestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_basestation_proto_rawDesc), len(file_msg_basestation_proto_rawDesc)))
	})
	return file_msg_basestation_proto_rawDescData
}

var file_msg_basestation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_basestation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_msg_basestation_proto_goTypes = []any{
	(ConnectionState)(0),                 // 0: msg.ConnectionState
	(*ProtoBasestationState)(nil),        // 1: msg.ProtoBasestationState
	(*ProtoBasestationMessage)(nil),      // 2: msg.ProtoBasestationMessage
	(*BasestationConnection)(nil),        // 3: msg.BasestationConnection
	(*BasestationStatus)(nil),            // 4: msg.BasestationStatus
	(*GeoLocation)(nil),                  // 5: msg.GeoLocation
	(*BasestationVariableMacStatus)(nil), // 6: msg.BasestationVariableMacStatus
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_msg_basestation_proto_depIdxs = []int32{
	0, // 0: msg.ProtoBasestationState.state:type_name -> msg.ConnectionState
	3, // 1: msg.ProtoBasestationMessage.con:type_name -> msg.BasestationConnection
	4, // 2: msg.ProtoBasestationMessage.status:type_name -> msg.BasestationStatus
	6, // 3: msg.ProtoBasestationMessage.vm_status:type_name -> msg.BasestationVariableMacStatus
	7, // 4: msg.BasestationConnection.ts:type_name -> google.protobuf.Timestamp
	7, // 5: msg.BasestationStatus.ts:type_name -> google.protobuf.Timestamp
	5, // 6: msg.BasestationStatus.geo_location:type_name -> msg.GeoLocation
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_msg_basestation_proto_init() }
func file_msg_basestation_proto_init() {
	if File_msg_basestation_proto != nil {
		return
	}
	file_msg_basestation_proto_msgTypes[1].OneofWrappers = []any{
		(*ProtoBasestationMessage_Con)(nil),
		(*ProtoBasestationMessage_Status)(nil),
		(*ProtoBasestationMessage_VmStatus)(nil),
	}
	file_msg_basestation_proto_msgTypes[2].OneofWrappers = []any{}
	file_msg_basestation_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_basestation_proto_rawDesc), len(file_msg_basestation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_basestation_proto_goTypes,
		DependencyIndexes: file_msg_basestation_proto_depIdxs,
		EnumInfos:         file_msg_basestation_proto_enumTypes,
		MessageInfos:      file_msg_basestation_proto_msgTypes,
	}.Build()
	File_msg_basestation_proto = out.File
	file_msg_basestation_proto_goTypes = nil
	file_msg_basestation_proto_depIdxs = nil
}
