// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: rsp/rsp.proto

package rsp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the current operation
	OpId int64 `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// Basestation EUI, 8 bytes little endian
	BsEui uint64 `protobuf:"varint,2,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// Command.
	//
	// Types that are valid to be assigned to V1:
	//
	//	*ProtoResponse_AttRsp
	//	*ProtoResponse_DetRsp
	//	*ProtoResponse_Err
	V1            isProtoResponse_V1 `protobuf_oneof:"v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoResponse) Reset() {
	*x = ProtoResponse{}
	mi := &file_rsp_rsp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoResponse) ProtoMessage() {}

func (x *ProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rsp_rsp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoResponse.ProtoReflect.Descriptor instead.
func (*ProtoResponse) Descriptor() ([]byte, []int) {
	return file_rsp_rsp_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoResponse) GetOpId() int64 {
	if x != nil {
		return x.OpId
	}
	return 0
}

func (x *ProtoResponse) GetBsEui() uint64 {
	if x != nil {
		return x.BsEui
	}
	return 0
}

func (x *ProtoResponse) GetV1() isProtoResponse_V1 {
	if x != nil {
		return x.V1
	}
	return nil
}

func (x *ProtoResponse) GetAttRsp() *EndnodeAttachResponse {
	if x != nil {
		if x, ok := x.V1.(*ProtoResponse_AttRsp); ok {
			return x.AttRsp
		}
	}
	return nil
}

func (x *ProtoResponse) GetDetRsp() *EndnodeDetachResponse {
	if x != nil {
		if x, ok := x.V1.(*ProtoResponse_DetRsp); ok {
			return x.DetRsp
		}
	}
	return nil
}

func (x *ProtoResponse) GetErr() *ErrorResponse {
	if x != nil {
		if x, ok := x.V1.(*ProtoResponse_Err); ok {
			return x.Err
		}
	}
	return nil
}

type isProtoResponse_V1 interface {
	isProtoResponse_V1()
}

type ProtoResponse_AttRsp struct {
	// Server attachment
	AttRsp *EndnodeAttachResponse `protobuf:"bytes,4,opt,name=att_rsp,json=attRsp,proto3,oneof"`
}

type ProtoResponse_DetRsp struct {
	// Server detachment
	DetRsp *EndnodeDetachResponse `protobuf:"bytes,5,opt,name=det_rsp,json=detRsp,proto3,oneof"`
}

type ProtoResponse_Err struct {
	Err *ErrorResponse `protobuf:"bytes,6,opt,name=err,proto3,oneof"`
}

func (*ProtoResponse_AttRsp) isProtoResponse_V1() {}

func (*ProtoResponse_DetRsp) isProtoResponse_V1() {}

func (*ProtoResponse_Err) isProtoResponse_V1() {}

type EndnodeAttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui uint64 `protobuf:"varint,1,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// End Point short address, only if not assigned by the Base Station
	ShAddr *uint32 `protobuf:"varint,2,opt,name=sh_addr,json=shAddr,proto3,oneof" json:"sh_addr,omitempty"`
	// 16 Byte End Point network session key
	NwkSessionKey []byte `protobuf:"bytes,3,opt,name=nwk_session_key,json=nwkSessionKey,proto3" json:"nwk_session_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndnodeAttachResponse) Reset() {
	*x = EndnodeAttachResponse{}
	mi := &file_rsp_rsp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndnodeAttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndnodeAttachResponse) ProtoMessage() {}

func (x *EndnodeAttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rsp_rsp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndnodeAttachResponse.ProtoReflect.Descriptor instead.
func (*EndnodeAttachResponse) Descriptor() ([]byte, []int) {
	return file_rsp_rsp_proto_rawDescGZIP(), []int{1}
}

func (x *EndnodeAttachResponse) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

func (x *EndnodeAttachResponse) GetShAddr() uint32 {
	if x != nil && x.ShAddr != nil {
		return *x.ShAddr
	}
	return 0
}

func (x *EndnodeAttachResponse) GetNwkSessionKey() []byte {
	if x != nil {
		return x.NwkSessionKey
	}
	return nil
}

type EndnodeDetachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui uint64 `protobuf:"varint,1,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// End Point signature, 4 bytes little endian
	Sign          uint32 `protobuf:"varint,2,opt,name=sign,proto3" json:"sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndnodeDetachResponse) Reset() {
	*x = EndnodeDetachResponse{}
	mi := &file_rsp_rsp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndnodeDetachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndnodeDetachResponse) ProtoMessage() {}

func (x *EndnodeDetachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rsp_rsp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndnodeDetachResponse.ProtoReflect.Descriptor instead.
func (*EndnodeDetachResponse) Descriptor() ([]byte, []int) {
	return file_rsp_rsp_proto_rawDescGZIP(), []int{2}
}

func (x *EndnodeDetachResponse) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

func (x *EndnodeDetachResponse) GetSign() uint32 {
	if x != nil {
		return x.Sign
	}
	return 0
}

type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_rsp_rsp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rsp_rsp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_rsp_rsp_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rsp_rsp_proto protoreflect.FileDescriptor

var file_rsp_rsp_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x72, 0x73, 0x70, 0x2f, 0x72, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x72, 0x73, 0x70, 0x22, 0xd7, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x6f, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x62,
	0x73, 0x5f, 0x65, 0x75, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x62, 0x73, 0x45,
	0x75, 0x69, 0x12, 0x35, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x73, 0x70, 0x2e, 0x45, 0x6e, 0x64, 0x6e, 0x6f, 0x64,
	0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x06, 0x61, 0x74, 0x74, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x07, 0x64, 0x65, 0x74,
	0x5f, 0x72, 0x73, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x73, 0x70,
	0x2e, 0x45, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x64, 0x65, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x26, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x72, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x42, 0x04, 0x0a, 0x02, 0x76, 0x31, 0x22, 0x8a,
	0x01, 0x0a, 0x15, 0x45, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x65, 0x75, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65,
	0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x45, 0x75, 0x69, 0x12, 0x1c, 0x0a, 0x07, 0x73, 0x68, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06, 0x73, 0x68,
	0x41, 0x64, 0x64, 0x72, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x77, 0x6b, 0x5f, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0d, 0x6e, 0x77, 0x6b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x42,
	0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x68, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x22, 0x4c, 0x0a, 0x15, 0x45,
	0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x65, 0x75, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x6e, 0x6f,
	0x64, 0x65, 0x45, 0x75, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x29, 0x0a, 0x0d, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x6d, 0x69, 0x6f, 0x74, 0x79, 0x2d, 0x62, 0x73,
	0x73, 0x63, 0x69, 0x2d, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x73, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_rsp_rsp_proto_rawDescOnce sync.Once
	file_rsp_rsp_proto_rawDescData []byte
)

func file_rsp_rsp_proto_rawDescGZIP() []byte {
	file_rsp_rsp_proto_rawDescOnce.Do(func() {
		file_rsp_rsp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rsp_rsp_proto_rawDesc), len(file_rsp_rsp_proto_rawDesc)))
	})
	return file_rsp_rsp_proto_rawDescData
}

var file_rsp_rsp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rsp_rsp_proto_goTypes = []any{
	(*ProtoResponse)(nil),         // 0: rsp.ProtoResponse
	(*EndnodeAttachResponse)(nil), // 1: rsp.EndnodeAttachResponse
	(*EndnodeDetachResponse)(nil), // 2: rsp.EndnodeDetachResponse
	(*ErrorResponse)(nil),         // 3: rsp.ErrorResponse
}
var file_rsp_rsp_proto_depIdxs = []int32{
	1, // 0: rsp.ProtoResponse.att_rsp:type_name -> rsp.EndnodeAttachResponse
	2, // 1: rsp.ProtoResponse.det_rsp:type_name -> rsp.EndnodeDetachResponse
	3, // 2: rsp.ProtoResponse.err:type_name -> rsp.ErrorResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rsp_rsp_proto_init() }
func file_rsp_rsp_proto_init() {
	if File_rsp_rsp_proto != nil {
		return
	}
	file_rsp_rsp_proto_msgTypes[0].OneofWrappers = []any{
		(*ProtoResponse_AttRsp)(nil),
		(*ProtoResponse_DetRsp)(nil),
		(*ProtoResponse_Err)(nil),
	}
	file_rsp_rsp_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rsp_rsp_proto_rawDesc), len(file_rsp_rsp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rsp_rsp_proto_goTypes,
		DependencyIndexes: file_rsp_rsp_proto_depIdxs,
		MessageInfos:      file_rsp_rsp_proto_msgTypes,
	}.Build()
	File_rsp_rsp_proto = out.File
	file_rsp_rsp_proto_goTypes = nil
	file_rsp_rsp_proto_depIdxs = nil
}
